/// Flutter icons Joyicon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Joyicon
///      fonts:
///       - asset: fonts/Joyicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Joyicon {
  Joyicon._();

  static const _kFontFam = 'Joyicon';

  static const IconData prey = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData prey_clicked = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData qt = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData qt_clicked = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData sermon = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData sermon_clicked = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData bible = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData bible_clicked = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData hymn = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData hymn_clicked = const IconData(0xe809, fontFamily: _kFontFam);
}
